-- v0 -> v1 (compatible with v1+): Latest schema
CREATE TABLE irc_ident(
    -- only: postgres
    rowid BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    -- only: sqlite (line commented)
--	rowid INTEGER PRIMARY KEY,
    mxid  TEXT NOT NULL,
    ident TEXT NOT NULL,

    CONSTRAINT irc_ident_mxid_unique UNIQUE (mxid),
    CONSTRAINT irc_ident_ident_unique UNIQUE (ident)
);
